### ISSUE TITLE
Fix Text on Symptom Buttons in Question 4

### ISSUE THREAD

**Issue by stefanbuttigieg** [COVID19-Malta/coronatest#10]
Fix the text of the Symptom Buttons from 'sore_throat' to 'Sore Throat', 'runny_nose' to 'Runny Nose', 'muscle_pain' to 'Muscle Pain', 'loss_of_smell' to 'Loss of Smell', 'loss_of_taste' to 'Loss of Taste' and 'diarrhoea' to 'Diarrhoea'

**Comment by jp-um** [comment]
Can you please paste a screenshot of what you are looking at.  This is what I am seeing (can you delete your browser cache?)

![image](https://user-images.githubusercontent.com/22983794/79796390-c17ee880-8355-11ea-88dd-239fedb681a0.png)

**Comment by stefanbuttigieg** [comment]
Indeed you are right! Closing this issue
