### ISSUE TITLE
Update Ministry for Health Logo

### ISSUE THREAD

**Issue by stefanbuttigieg** [COVID19-Malta/coronatest#11]
We need to change 'Ministry for Health' Logo to the official one 'Office of the Deputy Prime Minister' which is available [here](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRt-esPTTAOf7XtkrxV8-ed5FEfYI4DyNwAKl2oXYYCBkA6s0xm&usqp=CAU)

**Comment by jp-um** [comment]
Done, please test and close issue if satisfied.

**Comment by stefanbuttigieg** [comment]
Can we triple the size of the logo?
