### ISSUE TITLE
Remove the ability to detect IP

### ISSUE THREAD

**Issue by stefanbuttigieg** [COVID19-Malta/coronatest#18]
To stop collecting data about IP addresses

**Comment by stefanbuttigieg** [comment]
Remove IP Address but keep Session ID

**Comment by jp-um** [comment]
**FIxed.**  Please test and close issue. (Now saving empty string '' instead of IP, not super elegant perhaps, but works).

**Comment by stefanbuttigieg** [comment]
Sounds good. We can improve at a later stage on this. The most important is that we preserve privacy
